### ISSUE TITLE
`flow_view_deps()` and reprex

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/flow#125]
For some reason, I can't use `flow_view_deps()` in a reprex. Is there a trick?

**Comment by moodymudskipper** [comment]
It's because it's an htmlwidget.

Here is a workaround, you could do this then edit the code:

``` r
library(constructive)
out <- flow:::flow_view_deps(construct, out = tempfile(fileext = ".png"))
knitr::include_graphics(out)
```

![](https://i.imgur.com/w9wn26G.png)

<sup>Created on 2022-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Let's leave it open, maybe we can detect that we're in a reprex (or knitting more generally), and then we'd trigger this behaviour.
To be more robust we might need a superclass of "htmlwidget" and the printing method will do it.

**Comment by moodymudskipper** [comment]
To do : 

* Whenever `htmlwidgets::createWidget()` is called, add a class "flow_diagram" to the "htmlwidget" class, so it has class `c( "flow_diagram", "htmlwidget")`
* Modularize `flow:::save_nomnoml()` to extract an unexported function `widget_to_file()`
* Have `print.flow_diagram()` check if `isTRUE(getOption('knitr.in.progress'))`, if `TRUE`, call `widget_to_file()` and `knitr::include_graphics()`, if not, `NextMethod()`

**Comment by moodymudskipper** [comment]
While we're at it why don't we return a richer object : 
* it prints like a htmlwidget
* has a widget element
* has a data element

**Comment by moodymudskipper** [comment]
Should be fixed.

we return a "flow_diagram" object,  containing a widget, the data, and the nomnoml code. `print()` prints the widget, with a workaround when knitting.

Unfortunately when knitting the print() method doesn't return the input, but I assume it's a feature of `print()` that is rarely used in reprexes and reports.

``` r
x <- flow::flow_view_deps(constructive::construct)
names(x)
#> [1] "widget" "data"   "code"
flow::flow_view_deps(constructive::construct)
```

![](https://i.imgur.com/xTwjQlO.png)

<sup>Created on 2022-11-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
