### ISSUE TITLE
Is there a way to increase the resolution?

### ISSUE THREAD

**Issue by AdrianAntico** [moodymudskipper/flow#38]
@moodymudskipper I'd like to start off by saying this is a really cool package! 

Now to the request: I ran flow::flow_view() over a highly involved function and even after sending to a png and zooming in, there isn't enough resolution to see what's happening. Is this something that can be looked into? To me, having the ability to visualize a process becomes more important as the complexity of the function or script increases. 

I ran was the below and it's a function with a ton of parameters and calls to other functions that are themselves highly involved. 

```
flow::flow_view(RemixAutoML::AutoCatBoostChainLadder)
```

**Comment by moodymudskipper** [comment]
Hi @AdrianAntico and thanks for the kind words.

How did you save it to png ? Have you tried `out = "png"` ? When I try it on my side on the function I found on your repo I can zoom more than enough, see below : 

![ML](https://user-images.githubusercontent.com/18351714/90198969-a38d3600-ddd3-11ea-9941-738953eea103.gif)

If you don't see the same thing then it must by system dependent and I only have windows to test it unfortunately, but you might want to try to play with the `width` and `height` , they are forwarded to `htmlwidgets::createWidget()`, I've never needed them so not sure exactly what it'll change.

Try also `flow::flow_view(AutoCatBoostChainLadder, out = "html", svg = TRUE)` , it should render it as vector graphics in a webpage so you might be able to zoom better there.


Now there are other ways to alter the view. You could use `code = FALSE` not to display the code in blocks, as sometimes you can infer it from the logical path.

Because your code is very cleanly commented I think you'd enjoy the `prefix` feature but I'm embarassed to see it seems broken unfortunately, I hope you'll remember to check it later when I fix it. with `prefix = "#"` and `code = FALSE` you'll see your comments instead of the code below, which is nice to inspect the logic.

Finally there's a way to zoom quite literally, it's the range argument. It might require a bit of manual adjustments to choose a range that looks good but it works quite well still:

    flow::flow_view(AutoCatBoostChainLadder, range = 47:52)

![image](https://user-images.githubusercontent.com/18351714/90199752-ecde8500-ddd5-11ea-8858-ba6a842aa32e.png)


Please tell me how it works for you, your feedback is extremely valuable to me

**Comment by AdrianAntico** [comment]
@moodymudskipper Ah ha! I did not use the out = "png" argument. I ran it without and then used Rstudio to show the image which I then saved to png, which obviously is not the right way to do it. I was able to reproduce the image like you showed! Super thanks!

**Comment by moodymudskipper** [comment]
Good to know!
FYI if instead of "png" you provite a legit path to a png file it will save it there, and not open it automatically.

**Comment by AdrianAntico** [comment]
@moodymudskipper Even better!

**Comment by moodymudskipper** [comment]
Hi @AdrianAntico ,

I don't know if it's of interest for you but I've fixed the use the prefix argument, for your function you can use your comments as headers by setting prefix = "#" (all comments are headers in that case) .  The code can be shortened by applying also code = FALSE, in that case it's all described by headers : 

    flow_view(AutoCatBoostChainLadder, prefix = "#", code = FALSE, out = "png")

![Capture1](https://user-images.githubusercontent.com/18351714/90788243-e7b59480-e305-11ea-8857-65e891bd8551.PNG)

Or you can display the code only when headers are not available, using code = NA : 

    flow_view(AutoCatBoostChainLadder, prefix = "#", code = NA, out = "png")

![Capture2](https://user-images.githubusercontent.com/18351714/90788448-1df31400-e306-11ea-82cd-78be346d76b2.PNG)

**Comment by AdrianAntico** [comment]
@moodymudskipper Thanks for the update! I think the comment only version is very useful, maybe more so, since it's usually non-technical folks who make request for these types of documents.
